// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Voyage.Data;

#nullable disable

namespace Voyage.Migrations
{
    [DbContext(typeof(_AppDbContext))]
    [Migration("20251108044000_Create_SessionTable")]
    partial class Create_SessionTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Voyage.Data.Logger", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("LogSeverity")
                        .HasPrecision(1)
                        .HasColumnType("numeric");

                    b.Property<decimal>("LogType")
                        .HasPrecision(1)
                        .HasColumnType("numeric");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModifiedDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StackTrace")
                        .HasColumnType("varchar");

                    b.HasKey("LogId");

                    b.ToTable("_Log", (string)null);
                });

            modelBuilder.Entity("Voyage.Data.TableModels.UserEF", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(254)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModifiedDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Phone")
                        .HasPrecision(10)
                        .HasColumnType("numeric");

                    b.Property<decimal>("PhoneAreaCode")
                        .HasPrecision(5)
                        .HasColumnType("numeric");

                    b.Property<decimal>("PhoneCountryCode")
                        .HasPrecision(3)
                        .HasColumnType("numeric");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("varchar(75)");

                    b.Property<decimal>("UnitNumber")
                        .HasPrecision(5)
                        .HasColumnType("numeric");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("ZipCode")
                        .HasPrecision(16)
                        .HasColumnType("numeric");

                    b.HasKey("UserId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Voyage.Data.TableModels._MasterEF", b =>
                {
                    b.Property<int>("MasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MasterId"));

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.HasKey("MasterId");

                    b.ToTable("_Master", (string)null);
                });

            modelBuilder.Entity("Voyage.Data.TableModels._SessionEF", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SessionId"));

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("ExpiresAt")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("LastAccessed")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SessionKey")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("UserId")
                        .HasPrecision(10)
                        .HasColumnType("numeric");

                    b.HasKey("SessionId");

                    b.ToTable("Session", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
